### ISSUE TITLE
CHUNK BY not working since release

### ISSUE THREAD

**Issue by jason-godden** [VulknData/vulkn#63]
```python
>>> v.q("select k, max(m) from (select arrayJoin(['a','b']) as k, arrayJoin(range(0,10)) as m) group by k chunk by (k, 1)").show_sql()
Code: 62, e.displayText() = DB::Exception: Syntax error (query): failed at position 100: chunk by (k, 1). Expected one of: AND, OR, alias, UNION ALL, token, AS, WITH, HAVING, LIMIT, SETTINGS, FORMAT, NOT, BETWEEN, LIKE, IS, NOT LIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, Comma, Dot, Arrow, QuestionMark, ORDER BY, INTO OUTFILE, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xbd0920c in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x4fdc6e9 in /usr/bin/clickhouse
2. ? @ 0x4d3f528 in /usr/bin/clickhouse
3. mainEntryClickHouseFormat(int, char**) @ 0x516acd0 in /usr/bin/clickhouse
4. main @ 0x4f1ecf9 in /usr/bin/clickhouse
5. /build/glibc-LK5gWL/glibc-2.23/csu/../csu/libc-start.c:325: __libc_start_main @ 0x20830 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.23.so
6. _start @ 0x4f8247a in /usr/bin/clickhouse
 (version 20.2.1.2260 (official build))select k, max(m) from  (select arrayJoin(['a','b']) as k, arrayJoin(range(0,10)) as m)  group by k chunk by (k, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jason/code/vulkn/vulkn/datatable.py", line 173, in show_sql
    return sqlformat(statements[0].optimize())
  File "/home/jason/code/vulkn/vulkn/clickhouse/__init__.py", line 27, in sqlformat
    raise Exception
Exception
```

**Comment by jason-godden** [comment]
Fixed by #69.
