### ISSUE TITLE
Remove some limitations with VECTORIZE BY

### ISSUE THREAD

**Issue by jason-godden** [VulknData/vulkn#64]
VECTORIZE BY requires the vector column source/args are included in the final result and that a vector function call has an alias. These restrictions should be fixed/addressed.

This works as expected:

```python
>>> v.q("SELECT key, timestamp, metric, vectorDeltaLag(metric,1) AS `metric_delta` from (select arrayJoin(['a','b']) as key, toDateTime('2020-01-01 00:00:00') + interval metric hour as timestamp, arrayJoin(range(10)) as metric) vectorize by (key, timestamp)").s

  row  key    timestamp              metric    metric_delta
-----  -----  -------------------  --------  --------------
    1  b      2020-01-01 00:00:00         0             nan
    2  b      2020-01-01 01:00:00         1               1
    3  b      2020-01-01 02:00:00         2               1
    4  b      2020-01-01 03:00:00         3               1
    5  b      2020-01-01 04:00:00         4               1
    6  b      2020-01-01 05:00:00         5               1
    7  b      2020-01-01 06:00:00         6               1
    8  b      2020-01-01 07:00:00         7               1
    9  b      2020-01-01 08:00:00         8               1
   10  b      2020-01-01 09:00:00         9               1
   11  a      2020-01-01 00:00:00         0             nan
   12  a      2020-01-01 01:00:00         1               1
   13  a      2020-01-01 02:00:00         2               1
   14  a      2020-01-01 03:00:00         3               1
   15  a      2020-01-01 04:00:00         4               1
   16  a      2020-01-01 05:00:00         5               1
   17  a      2020-01-01 06:00:00         6               1
   18  a      2020-01-01 07:00:00         7               1
   19  a      2020-01-01 08:00:00         8               1
   20  a      2020-01-01 09:00:00         9               1

(20 rows)
```

Fails because metric isn't included in the final result.

```python
>>> v.q("SELECT key, timestamp, vectorDeltaLag(metric,1) AS `metric_delta` from (select arrayJoin(['a','b']) as key, toDateTime('2020-01-01 00:00:00') + interval metric hour as timestamp, arrayJoin(range(10)) as metric) vectorize by (key, timestamp)").s
Code: 62, e.displayText() = DB::Exception: Syntax error (query): failed at position 36 (line 4, col 5): ,
    v4124723699656693175_1 - v4124723699656693175_2 AS `metric_delta`
FROM
(
    SELECT
        key,
        arraySort(x -> x.1, groupArray((timestamp, ))) AS. Expected one of: CAST, NULL, multiplicative expression, additive expression, comparison expression, logical-NOT expression, logical-AND expression, logical-OR expression, case, function, COLUMNS, array, token, parenthesized expression, SELECT subquery, identifier, compound identifier, asterisk, qualified asterisk, COLUMNS matcher, CAST expression, SUBSTRING expression, TRIM expression, LEFT expression, RIGHT expression, EXTRACT expression, DATE_ADD expression, DATE_DIFF expression, number, string literal, literal, substitution, element of expression, SUBSTRING, LEFT, RIGHT, EXTRACT, DATEADD, DATE_ADD, TIMESTAMPADD, TIMESTAMP_ADD, DATESUB, DATE_SUB, TIMESTAMPSUB, TIMESTAMP_SUB, INTERVAL, LTRIM, RTRIM, TRIM, DATEDIFF, DATE_DIFF, TIMESTAMPDIFF, TIMESTAMP_DIFF, NOT, list of elements, array element expression, tuple element expression, unary minus expression, INTERVAL operator expression, BETWEEN expression, nullity checking, lambda expression, OpeningRoundBracket, Arrow, CASE, expression with optional alias, string concatenation expression, element of expression with optional alias, list, delimited by binary operators, list, delimited by operator of variable arity, expression with prefix unary operator, expression with ternary operator, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xbd0920c in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x4fdc6e9 in /usr/bin/clickhouse
2. ? @ 0x4d3f528 in /usr/bin/clickhouse
3. mainEntryClickHouseFormat(int, char**) @ 0x516acd0 in /usr/bin/clickhouse
4. main @ 0x4f1ecf9 in /usr/bin/clickhouse
5. /build/glibc-LK5gWL/glibc-2.23/csu/../csu/libc-start.c:325: __libc_start_main @ 0x20830 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.23.so
6. _start @ 0x4f8247a in /usr/bin/clickhouse
 (version 20.2.1.2260 (official build))SELECT
    key,
    timestamp,
    ,
    v4124723699656693175_1 - v4124723699656693175_2 AS `metric_delta`
FROM
(
    SELECT
        key,
        arraySort(x -> x.1, groupArray((timestamp, ))) AS `--#v`
    FROM  (select arrayJoin(['a','b']) as key, toDateTime('2020-01-01 00:00:00') + interval metric hour as timestamp, arrayJoin(range(10)) as metric)  
    GROUP BY key
)
ARRAY JOIN
    `--#v`.1 AS `timestamp`,
    __metric AS v4124723699656693175_1,
    arrayConcat(arrayWithConstant(1, NULL), arraySlice(__metric, 1, -1)) AS v4124723699656693175_2
SETTINGS enable_unaligned_array_join = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jason/code/vulkn/vulkn/datatable.py", line 247, in show
    return self.exec().show()
  File "/home/jason/code/vulkn/vulkn/utils.py", line 35, in wrap
    r = f(*args, **kwargs)
  File "/home/jason/code/vulkn/vulkn/datatable.py", line 227, in exec
    return self._ctx._conn.select(statements[0].optimize())
  File "/home/jason/code/vulkn/vulkn/clickhouse/client/cli.py", line 132, in select
    q = self._q(cli, query, settings=settings)
  File "/home/jason/code/vulkn/vulkn/clickhouse/client/cli.py", line 115, in _q
    log.log(LogLevels.SQL, sqlformat(query))
  File "/home/jason/code/vulkn/vulkn/clickhouse/__init__.py", line 27, in sqlformat
    raise Exception
Exception
```

Fails because no alias is provided for vectorDeltaLag(metric,1).

```python
>>> v.q("SELECT key, timestamp, metric, vectorDeltaLag(metric,1) from (select arrayJoin(['a','b']) as key, toDateTime('2020-01-01 00:00:00') + interval metric hour as timestamp, arrayJoin(range(10)) as metric) vectorize by (key, timestamp)").sCode: 62, e.displayText() = DB::Exception: Syntax error (query): failed at position 77 (line 9, col 9): key,
        arraySort(x -> x.1, groupArray((timestamp, metric))) AS `--#v`
    FROM  (select arrayJoin(['a','b']) as key, toDateTime('2020-01-01 00:00:00') + i. Expected one of: AND, OR, alias, token, AS, NOT, BETWEEN, LIKE, IS, NOT LIKE, IN, NOT IN, GLOBAL IN, GLOBAL NOT IN, Comma, Dot, Arrow, QuestionMark, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xbd0920c in /usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x4fdc6e9 in /usr/bin/clickhouse
2. ? @ 0x4d3f528 in /usr/bin/clickhouse
3. mainEntryClickHouseFormat(int, char**) @ 0x516acd0 in /usr/bin/clickhouse
4. main @ 0x4f1ecf9 in /usr/bin/clickhouse
5. /build/glibc-LK5gWL/glibc-2.23/csu/../csu/libc-start.c:325: __libc_start_main @ 0x20830 in /usr/lib/debug/lib/x86_64-linux-gnu/libc-2.23.so
6. _start @ 0x4f8247a in /usr/bin/clickhouse
 (version 20.2.1.2260 (official build))SELECT
    key,
    timestamp,
    `metric`,
    
FROM
(
    SELECT
        key,
        arraySort(x -> x.1, groupArray((timestamp, metric))) AS `--#v`
    FROM  (select arrayJoin(['a','b']) as key, toDateTime('2020-01-01 00:00:00') + interval metric hour as timestamp, arrayJoin(range(10)) as metric)  
    GROUP BY key
)
ARRAY JOIN
    `--#v`.1 AS `timestamp`,
    `--#v`.2 AS `metric`
SETTINGS enable_unaligned_array_join = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jason/code/vulkn/vulkn/datatable.py", line 247, in show
    return self.exec().show()
  File "/home/jason/code/vulkn/vulkn/utils.py", line 35, in wrap
    r = f(*args, **kwargs)
  File "/home/jason/code/vulkn/vulkn/datatable.py", line 227, in exec
    return self._ctx._conn.select(statements[0].optimize())
  File "/home/jason/code/vulkn/vulkn/clickhouse/client/cli.py", line 132, in select
    q = self._q(cli, query, settings=settings)
  File "/home/jason/code/vulkn/vulkn/clickhouse/client/cli.py", line 115, in _q
    log.log(LogLevels.SQL, sqlformat(query))
  File "/home/jason/code/vulkn/vulkn/clickhouse/__init__.py", line 27, in sqlformat
    raise Exception
Exception
```

**Comment by jason-godden** [comment]
Most issues fixed in #67. Still requires key and sort/timestamp column to be included (or will inject them back in if not present). May be addressed in a future review of this function (or Yandex will implement something similar ;) ).
