### ISSUE TITLE
CHUNK BY WHERE clause bracket syntax error

### ISSUE THREAD

**Issue by jason-godden** [VulknData/vulkn#73]
```python
>>> v.q('select key, histogram(10)(bytes) from timeseries_devices group by key chunk by (key, 2)').s
Received exception from server (version 20.2.1):
Code: 46. DB::Exception: Received from localhost:9001. DB::Exception: Unknown table function WHERE. 
Time elapsed: 89.069 ms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jason/code/vulkn-venv/lib/python3.7/site-packages/vulkn/datatable.py", line 247, in show
    return self.exec().show()
  File "/home/jason/code/vulkn-venv/lib/python3.7/site-packages/vulkn/recordset.py", line 177, in show
    table = self.to_pandas().values[0:1000].tolist()
  File "/home/jason/code/vulkn-venv/lib/python3.7/site-packages/vulkn/recordset.py", line 161, in to_pandas
    infer_datetime_format=True)
  File "/home/jason/code/vulkn-venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/jason/code/vulkn-venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/jason/code/vulkn-venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/jason/code/vulkn-venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/jason/code/vulkn-venv/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
>>> v.q('select key, histogram(10)(bytes) from timeseries_devices group by key chunk by (key, 2)').show_sql()
'SELECT key, histogram(10)(bytes) FROM WHERE((cityHash64(key) % 2) = 0) AS timeseries_devices GROUP BY key UNION ALL SELECT key, histogram(10)(bytes) FROM WHERE((cityHash64(key) % 2) = 1) AS timeseries_devices GROUP BY key;'

```

**Comment by jason-godden** [comment]
Fixed.
